import { PurchaseRequest } from "@/interfaces/PurchaseRequest";
import { Vendor } from "@/interfaces/Vendors";

export const PARTS = [
  {
    label: "Part 1",
    value: "part 1",
  },
  {
    label: "Part 2",
    value: "part 2",
  },
  {
    label: "Part 3",
    value: "part 3",
  },
  {
    label: "Part 4",
    value: "part 4",
  },
];
export const UNITS = [
  {
    label: "V (Voltage)",
    value: "v",
  },
  {
    label: "Ah (Capacity)",
    value: "ah",
  },
  {
    label: "Kg (Kilogram)",
    value: "kg",
  },
  {
    label: "units (Units)",
    value: "units",
  },
];
export const VENDORS = [
  {
    label: "Vendor 1",
    value: "Vendor 1",
  },

  {
    label: "Vendor 2",
    value: "Vendor 2",
  },

  {
    label: "Vendor 3",
    value: "Vendor 3",
  },

  {
    label: "Vendor 4",
    value: "Vendor 4",
  },
];
export const PO = [
  {
    label: "PO-1",
    value: "PO-1",
  },
  {
    label: "PO-2",
    value: "PO-2",
  },
  {
    label: "PO-3",
    value: "PO-3",
  },
  {
    label: "PO-4",
    value: "PO-4",
  },
];
export const STATUSES = [
  {
    label: "Loss On Line",
    value: "lol",
  },

  {
    label: "Quality Reject",
    value: "qr",
  },

  {
    label: "Positive Adjustment",
    value: "pa",
  },

  {
    label: "Production Return",
    value: "pr",
  },
];

export const INITIAL_CONTACT_PERSON_DETAILS = {
  country_code: "+91",
  designation: "",
  email: "",
  first_name: "",
  last_name: "",
  phone: "",
  address: "",
};

export const CONTACT_PERSON_INPUTS = [
  {
    key: "first_name",
    name: "First Name",
    id: "contactPersonaFirstName",
    type: "input",
    inputType: "text",
    placeholder: "First Name",
  },
  {
    key: "last_name",
    name: "Last Name",
    id: "contactPersonaLastName",
    type: "input",
    inputType: "text",
    placeholder: "Last Name",
  },
  {
    key: "email",
    name: "Email",
    id: "contactPersonaEmail",
    type: "input",
    inputType: "email",
    placeholder: "example@gmail.com",
  },
  {
    key: "phone",
    name: "Phone",
    id: "contactPersonaPhone",
    type: "input",
    inputType: "text",
    placeholder: "9597414840",
  },
  {
    key: "address",
    name: "Address",
    id: "contactPersonAddress",
    type: "input",
    inputType: "text",
    placeholder: "Delhi",
  },
  {
    key: "designation",
    name: "Designation",
    id: "contactPersonDesignation",
    type: "input",
    inputType: "text",
    placeholder: "Manager",
  },
];

export const dummyData: PurchaseRequest[] = [
  {
    id: 1,
    created_at: "2024-12-01T10:00:00Z",
    created_by: 1,
    enterprise_client: {
      address_line_1: "123 Main Street",
      address_line_2: "Suite 101",
      city_id: 1,
      code: "ENT001",
      contact_persons: [
        {
          first_name: "John",
          last_name: "Doe",
          address: "",
          country_code: "",
          designation: "CEO",
          email: "john.doe@example.com",
          phone: "1234567890",
        },
      ],
      country_id: 1,
      gst_number: "29ABCDE1234F2Z5",
      id: 1,
      name: "NIKHIL",
      pan_number: "FWEPR1234D",
      pincode: "110084",
      state_id: 1,
    },
    enterprise_client_id: 1,
    is_deleted: false,
    items: [
      {
        assigned_quantity: 10,
        created_at: "2024-12-01T10:10:00Z",
        created_by: 1,
        id: 1,
        product: {
          data: { color: "red", size: "M" },
          description: "Premium cotton T-shirt",
          hsn_code: "610910",
          manufacturer_id: 1,
          manufacturer_sku_code: "SKU001",
          name: "T-Shirt",
          unspsc: "12345678",
          uom_id: 1,
          id: 1,
        },
        quantity: 10,
        status: "Pending",
        updated_at: "2024-12-01T11:00:00Z",
        updated_by: 2,
      },
    ],
    reference_no: "PR001",
    status: "Pending",
    updated_at: "2024-12-01T12:00:00Z",
    updated_by: 2,
  },
  {
    id: 2,
    created_at: "2024-12-02T10:00:00Z",
    created_by: 2,
    enterprise_client: {
      address_line_1: "456 Elm Street",
      address_line_2: "Floor 3",
      city_id: 2,
      code: "ENT002",
      contact_persons: [
        {
          first_name: "Jane",
          last_name: "Smith",
          address: "",
          country_code: "",
          designation: "CEO",
          email: "jane.smith@example.com",
          phone: "9876543210",
        },
      ],
      country_id: 2,
      gst_number: "19EFGHI5678J9K6",
      id: 2,
      name: "ALPHA CORP",
      pan_number: "GHJPR5678Q",
      pincode: "560001",
      state_id: 2,
    },
    enterprise_client_id: 2,
    is_deleted: false,
    items: [
      {
        assigned_quantity: 20,
        created_at: "2024-12-02T10:20:00Z",
        created_by: 2,
        id: 2,
        product: {
          data: { capacity: "500GB", type: "SSD" },
          description: "Solid State Drive",
          hsn_code: "847170",
          manufacturer_id: 2,
          manufacturer_sku_code: "SSD500GB",
          name: "SSD Drive",
          unspsc: "43211503",
          uom_id: 2,
          id: 2,
        },
        quantity: 20,
        status: "Approved",
        updated_at: "2024-12-02T11:00:00Z",
        updated_by: 3,
      },
    ],
    reference_no: "PR002",
    status: "Approved",
    updated_at: "2024-12-02T12:00:00Z",
    updated_by: 3,
  },
  {
    id: 3,
    created_at: "2024-12-03T10:00:00Z",
    created_by: 3,
    enterprise_client: {
      address_line_1: "789 Oak Avenue",
      address_line_2: "Building B",
      city_id: 3,
      code: "ENT003",
      contact_persons: [
        {
          first_name: "Alice",
          last_name: "Brown",
          address: "",
          country_code: "",
          designation: "CEO",
          email: "alice.brown@example.com",
          phone: "1122334455",
        },
      ],
      country_id: 3,
      gst_number: "27JKL0123456M3Z2",
      id: 3,
      name: "OMEGA INC",
      pan_number: "JHKPR3456T",
      pincode: "400001",
      state_id: 3,
    },
    enterprise_client_id: 3,
    is_deleted: false,
    items: [
      {
        assigned_quantity: 5,
        created_at: "2024-12-03T10:30:00Z",
        created_by: 3,
        id: 3,
        product: {
          data: { material: "steel", dimensions: "10x5x2" },
          description: "Steel Plates",
          hsn_code: "731815",
          manufacturer_id: 3,
          manufacturer_sku_code: "STPL1234",
          name: "Steel Plate",
          unspsc: "30262303",
          uom_id: 3,
          id: 3,
        },
        quantity: 5,
        status: "Shipped",
        updated_at: "2024-12-03T11:00:00Z",
        updated_by: 4,
      },
    ],
    reference_no: "PR003",
    status: "Shipped",
    updated_at: "2024-12-03T12:00:00Z",
    updated_by: 4,
  },
  {
    id: 4,
    created_at: "2024-12-04T10:00:00Z",
    created_by: 4,
    enterprise_client: {
      address_line_1: "321 Pine Road",
      address_line_2: "Block C",
      city_id: 4,
      code: "ENT004",
      contact_persons: [
        {
          first_name: "Bob",
          last_name: "Green",
          address: "",
          country_code: "",
          designation: "CEO",
          email: "bob.green@example.com",
          phone: "5566778899",
        },
      ],
      country_id: 4,
      gst_number: "23OPQR6789S1Y8",
      id: 4,
      name: "DELTA LTD",
      pan_number: "OPQPR6789U",
      pincode: "600001",
      state_id: 4,
    },
    enterprise_client_id: 4,
    is_deleted: false,
    items: [
      {
        assigned_quantity: 15,
        created_at: "2024-12-04T10:40:00Z",
        created_by: 4,
        id: 4,
        product: {
          data: { weight: "2kg", color: "blue" },
          description: "Plastic Containers",
          hsn_code: "392310",
          manufacturer_id: 4,
          manufacturer_sku_code: "PCON5678",
          name: "Container",
          unspsc: "24112201",
          uom_id: 4,
          id: 4,
        },
        quantity: 15,
        status: "Delivered",
        updated_at: "2024-12-04T11:00:00Z",
        updated_by: 5,
      },
    ],
    reference_no: "PR004",
    status: "Delivered",
    updated_at: "2024-12-04T12:00:00Z",
    updated_by: 5,
  },
  {
    id: 5,
    created_at: "2024-12-05T10:00:00Z",
    created_by: 5,
    enterprise_client: {
      address_line_1: "654 Cedar Lane",
      address_line_2: "Warehouse",
      city_id: 5,
      code: "ENT005",
      contact_persons: [
        {
          first_name: "Eve",
          last_name: "White",
          address: "",
          country_code: "",
          designation: "CEO",
          email: "eve.white@example.com",
          phone: "6677889900",
        },
      ],
      country_id: 5,
      gst_number: "33UVWXYZ1234A7Z8",
      id: 5,
      name: "BETA GROUP",
      pan_number: "UVWXY1234Z",
      pincode: "700001",
      state_id: 5,
    },
    enterprise_client_id: 5,
    is_deleted: false,
    items: [
      {
        assigned_quantity: 50,
        created_at: "2024-12-05T10:50:00Z",
        created_by: 5,
        id: 5,
        product: {
          data: { power: "100W", type: "LED" },
          description: "LED Bulbs",
          hsn_code: "940510",
          manufacturer_id: 5,
          manufacturer_sku_code: "LEDB100",
          name: "LED Bulb",
          unspsc: "39101628",
          uom_id: 5,
          id: 5,
        },
        quantity: 50,
        status: "Pending",
        updated_at: "2024-12-05T11:00:00Z",
        updated_by: 6,
      },
    ],
    reference_no: "PR005",
    status: "Pending",
    updated_at: "2024-12-05T12:00:00Z",
    updated_by: 6,
  },
];

export const dummyVendors: Vendor[] = [
  {
    id: 1,
    name: "Tech Solutions",
    address: "123 Innovation Street",
    country_id: 1,
    state_id: 2,
    city_id: 3,
    gstin: "29ABCDE1234F2Z5",
    pan: "ABCDE1234F",
    contact_persons: [
      {
        first_name: "John",
        last_name: "Doe",
        email: "john.doe@techsolutions.com",
        phone: "9876543210",
        country_code: "+91",
        designation: "Manager",
        address: "123 Innovation Street",
      },
      {
        first_name: "Jane",
        last_name: "Smith",
        email: "jane.smith@techsolutions.com",
        phone: "8765432190",
        country_code: "+91",
        designation: "Sales Head",
        address: "456 Tech Park",
      },
    ],
    data: {
      type: "Preferred",
      rating: 4.5,
    },
    phone: "9876543210",
    email: "info@techsolutions.com",
  },
  {
    id: 2,
    name: "Industrial Supplies Inc.",
    address: "789 Manufacturing Blvd",
    country_id: 2,
    state_id: 4,
    city_id: 5,
    gstin: "19EFGHI5678J9K6",
    pan: "EFGHI5678J",
    contact_persons: [
      {
        first_name: "Alice",
        last_name: "Brown",
        email: "alice.brown@industrialsupplies.com",
        phone: "1234567890",
        country_code: "+44",
        designation: "Procurement Officer",
        address: "Warehouse Lane, Sector 3",
      },
    ],
    data: {
      type: "Standard",
      rating: 3.8,
    },
    phone: "1234567890",
    email: "support@industrialsupplies.com",
  },
  {
    id: 3,
    name: "Construction World",
    address: "456 Builder Road",
    country_id: 3,
    state_id: 1,
    city_id: 7,
    gstin: "27JKL0123456M3Z2",
    pan: "JKL0123456",
    contact_persons: [
      {
        first_name: "Robert",
        last_name: "Taylor",
        email: "robert.taylor@constructionworld.com",
        phone: "9988776655",
        country_code: "+61",
        designation: "Operations Manager",
        address: "Head Office, Suite 203",
      },
    ],
    data: {
      type: "Critical",
      rating: 4.9,
    },
    phone: "9988776655",
    email: "contact@constructionworld.com",
  },
];

export const dummyPO = [
  {
    poNo: 1001,
    date: "2024-12-01",
    vendor: "Tech Solutions",
    amount: 25000.5,
    status: "Pending",
  },
  {
    poNo: 1002,
    date: "2024-12-02",
    vendor: "Industrial Supplies Inc.",
    amount: 48900.0,
    status: "Approved",
  },
  {
    poNo: 1003,
    date: "2024-12-03",
    vendor: "Construction World",
    amount: 31000.75,
    status: "Shipped",
  },
  {
    poNo: 1004,
    date: "2024-12-04",
    vendor: "Tech Solutions",
    amount: 15000.0,
    status: "Delivered",
  },
  {
    poNo: 1005,
    date: "2024-12-05",
    vendor: "Industrial Supplies Inc.",
    amount: 52000.25,
    status: "Pending",
  },
];
